# Generated by Django 5.1.3 on 2025-01-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashkart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='_cvv',
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
